import React, { useState } from 'react';
import {
  BookOpen, FileUp, Users, Share2, Camera, Mic,
  BarChart2, Settings, ChevronDown, ChevronUp,
  ExternalLink, MessageCircle, Mail,
  CheckCircle2, AlertTriangle, Zap, Database,
} from 'lucide-react';
import EvaluationMetrics from './EvaluationMetrics';

/* ── FAQ data ─────────────────────────────────────────────────── */
const FAQS = [
  {
    q: 'How do I upload multiple CVs at once?',
    a: 'Go to CV Ingestion and drag-and-drop multiple PDF or DOCX files onto the upload zone, or click to browse and select multiple files. The system processes them in parallel and adds each candidate to the pool automatically.',
  },
  {
    q: 'What file formats are supported?',
    a: 'PDF (.pdf) and Microsoft Word (.docx) files are supported. Each file must be under 10 MB. Other formats like .doc, .txt, or images are not currently supported.',
  },
  {
    q: 'How is the match score calculated?',
    a: 'The match score is generated by the NLP engine after parsing the CV. It evaluates skills, experience level, education, and role alignment against the job requirements configured in Settings → NLP & Parsing.',
  },
  {
    q: 'What does the Knowledge Graph show?',
    a: 'Graph Search offers Force Graph and D3.js views of candidates and skills, plus a link to Neo4j Browser/Bloom for the live database graph.',
  },
  {
    q: 'How does Face Recognition work?',
    a: 'Upload an interview screenshot or use live camera mode. The backend runs OpenCV + FER on your image and returns emotion scores (Confident, Focused, Neutral, Happy, Nervous).',
  },
  {
    q: 'How does Voice Stress Detection work?',
    a: 'Upload audio or record live. Librosa acoustic analysis returns stress score (0–100), words-per-minute, pause count, and trait scores for Clarity, Pace, Confidence, Fluency, and Tone Variation.',
  },
  {
    q: 'Why is the backend showing "Not connected"?',
    a: 'The frontend is currently running in mock mode. To connect the Python Flask backend, go to Settings → Database, enter the backend URL (default: http://localhost:5000) and Neo4j credentials, then click "Ping Backend" and "Test Connection".',
  },
  {
    q: 'How do I remove a candidate from the pool?',
    a: 'On the Candidates page, each candidate row has a red trash icon on the right. Click it to remove that candidate. You can also clear all candidates from Settings → Data & Privacy → Danger Zone.',
  },
];

/* ── Guide cards ──────────────────────────────────────────────── */
const GUIDES = [
  {
    icon: FileUp,
    color: '#1a5c38',
    title: 'Upload & Parse CVs',
    steps: [
      'Navigate to CV Ingestion in the sidebar',
      'Drag & drop PDF or DOCX files onto the upload zone',
      'Click "Analyse CVs" to start batch processing',
      'Expand each file card to review extracted data',
      'Parsed candidates appear automatically in the Candidate Pool',
    ],
  },
  {
    icon: Users,
    color: '#3b82f6',
    title: 'Review Candidates',
    steps: [
      'Go to Candidates to see all parsed profiles',
      'Use the role filter and sort controls to narrow results',
      'Click any candidate row to open the detail modal',
      'Click "View Intelligence Graph" for the deep-dive graph',
      'Use the remove button to exclude candidates',
    ],
  },
  {
    icon: Camera,
    color: '#8b5cf6',
    title: 'Run Interview Analysis',
    steps: [
      'Go to Face Recognition or Voice Analysis',
      'Choose Upload or Live mode',
      'Upload interview footage or record live',
      'Click Analyse to get emotion / stress scores',
      'View results in Result Analysis for combined scoring',
    ],
  },
  {
    icon: Database,
    color: '#f59e0b',
    title: 'Connect the Backend',
    steps: [
      'Start the Python Flask server (python app.py)',
      'Start Neo4j database (default port 7687)',
      'Go to Settings → Database',
      'Enter Neo4j URI, username, and password',
      'Click "Test Connection" and "Ping Backend"',
    ],
  },
];

/* ── Keyboard shortcuts ───────────────────────────────────────── */
const SHORTCUTS = [
  { keys: ['Ctrl', 'K'], action: 'Open global search' },
  { keys: ['Ctrl', 'U'], action: 'Go to CV Ingestion' },
  { keys: ['Ctrl', 'C'], action: 'Go to Candidates' },
  { keys: ['Ctrl', 'G'], action: 'Go to Graph Search' },
  { keys: ['Esc'],       action: 'Close modal / drawer' },
];

/* ══════════════════════════════════════════════════════════════
   HELP PAGE
══════════════════════════════════════════════════════════════ */
const Help = () => {
  const [openFaq, setOpenFaq] = useState(null);

  return (
    <div className="animate-fade-up" style={{ display: 'flex', flexDirection: 'column', gap: '2rem', maxWidth: '900px' }}>

      {/* Hero */}
      <div style={{
        padding: '2rem',
        borderRadius: 'var(--r-2xl)',
        background: 'linear-gradient(145deg, #1a5c38 0%, #0d3320 100%)',
        color: '#fff',
        position: 'relative',
        overflow: 'hidden',
      }}>
        <div style={{ position: 'absolute', top: '-30px', right: '-30px', width: '180px', height: '180px', borderRadius: '50%', background: 'rgba(34,197,94,0.1)' }} />
        <div style={{ position: 'absolute', bottom: '-20px', left: '40%', width: '120px', height: '120px', borderRadius: '50%', background: 'rgba(34,197,94,0.07)' }} />
        <div style={{ position: 'relative' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
            <div style={{ width: '40px', height: '40px', borderRadius: 'var(--r-md)', background: 'rgba(255,255,255,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <BookOpen size={20} color="#4ade80" />
            </div>
            <h2 style={{ fontSize: '1.4rem', color: '#fff', margin: 0 }}>Help & Documentation</h2>
          </div>
          <p style={{ fontSize: '0.9rem', color: 'rgba(255,255,255,0.7)', lineHeight: '1.6', maxWidth: '500px' }}>
            Everything you need to use SmartHire Insights — from uploading CVs to connecting the backend and running interview analysis.
          </p>
        </div>
      </div>

      {/* Quick links */}
      <div>
        <h3 style={{ fontSize: '0.95rem', marginBottom: '1rem' }}>Quick Navigation</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: '0.75rem' }} className="stagger">
          {[
            { id: 'guides',    label: 'Getting Started', icon: Zap,         color: '#1a5c38' },
            { id: 'faq',       label: 'FAQ',             icon: MessageCircle,color: '#3b82f6' },
            { id: 'shortcuts', label: 'Shortcuts',       icon: Settings,     color: '#8b5cf6' },
            { id: 'contact',   label: 'Contact',         icon: Mail,         color: '#f59e0b' },
          ].map(({ id, label, icon: Icon, color }) => (
            <a
              key={id}
              href={`#${id}`}
              style={{
                display: 'flex', alignItems: 'center', gap: '0.625rem',
                padding: '0.875rem 1rem',
                borderRadius: 'var(--r-lg)',
                background: 'var(--bg-surface)',
                border: '1px solid var(--border)',
                textDecoration: 'none',
                color: 'var(--text-primary)',
                fontSize: '0.85rem', fontWeight: '600',
                transition: 'var(--transition)',
              }}
              className="card-interactive"
            >
              <div style={{ width: '28px', height: '28px', borderRadius: 'var(--r-sm)', background: `${color}18`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                <Icon size={14} color={color} />
              </div>
              {label}
            </a>
          ))}
        </div>
      </div>

      {/* Getting started guides */}
      <div id="guides">
        <h3 style={{ fontSize: '0.95rem', marginBottom: '1rem' }}>Getting Started Guides</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(380px, 1fr))', gap: '1rem' }}>
          {GUIDES.map((g, i) => (
            <GuideCard key={i} guide={g} delay={i * 60} />
          ))}
        </div>
      </div>

      {/* FAQ */}
      <div id="faq">
        <h3 style={{ fontSize: '0.95rem', marginBottom: '1rem' }}>Frequently Asked Questions</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          {FAQS.map((faq, i) => (
            <FaqItem
              key={i}
              faq={faq}
              open={openFaq === i}
              onToggle={() => setOpenFaq(openFaq === i ? null : i)}
            />
          ))}
        </div>
      </div>

      {/* Keyboard shortcuts */}
      <div id="shortcuts">
        <h3 style={{ fontSize: '0.95rem', marginBottom: '1rem' }}>Keyboard Shortcuts</h3>
        <div className="card" style={{ padding: '1.25rem' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0' }}>
            {SHORTCUTS.map((s, i) => (
              <div key={i} style={{
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                padding: '0.75rem 0',
                borderBottom: i < SHORTCUTS.length - 1 ? '1px solid var(--border)' : 'none',
              }}>
                <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>{s.action}</span>
                <div style={{ display: 'flex', gap: '0.3rem' }}>
                  {s.keys.map(k => (
                    <kbd key={k} style={{
                      padding: '0.2rem 0.5rem',
                      borderRadius: 'var(--r-xs)',
                      background: 'var(--bg-elevated)',
                      border: '1px solid var(--border-strong)',
                      fontSize: '0.72rem', fontFamily: 'var(--font-mono)',
                      fontWeight: '600', color: 'var(--text-primary)',
                    }}>{k}</kbd>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Evaluation metrics */}
      <div id="evaluation">
        <h3 style={{ fontSize: '0.95rem', marginBottom: '1rem' }}>Pipeline Evaluation (P/R/F1)</h3>
        <EvaluationMetrics />
      </div>

      {/* System status */}
      <div>
        <h3 style={{ fontSize: '0.95rem', marginBottom: '1rem' }}>System Status</h3>
        <div className="card" style={{ padding: '1.25rem' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.875rem' }}>
            {[
              { label: 'Frontend (React)',         status: 'online',  note: 'Running on localhost:5173' },
              { label: 'Python Flask Backend',     status: 'offline', note: 'Not started — run python app.py' },
              { label: 'Neo4j Graph Database',     status: 'offline', note: 'Not connected — configure in Settings' },
              { label: 'FER (OpenCV + FER)',       status: 'online',  note: 'Real analysis via POST /api/face-analysis' },
              { label: 'Voice Stress (librosa)',   status: 'online',  note: 'Real acoustics via POST /api/voice-analysis' },
              { label: 'NLTK preprocessing',     status: 'online',  note: 'Tokenization & lemmatization in CV pipeline' },
              { label: 'D3.js visualization',      status: 'online',  note: 'Graph Search → D3.js tab' },
            ].map(s => (
              <div key={s.label} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '0.5rem' }}>
                <div>
                  <p style={{ fontSize: '0.85rem', fontWeight: '600' }}>{s.label}</p>
                  <p style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>{s.note}</p>
                </div>
                <span className={`badge ${s.status === 'online' ? 'badge-success' : s.status === 'mock' ? 'badge-warning' : 'badge-danger'}`}>
                  {s.status === 'online' ? <CheckCircle2 size={10} /> : <AlertTriangle size={10} />}
                  {s.status === 'online' ? 'Online' : s.status === 'mock' ? 'Mock Mode' : 'Offline'}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Contact */}
      <div id="contact">
        <h3 style={{ fontSize: '0.95rem', marginBottom: '1rem' }}>Contact & Support</h3>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
          <ContactCard
            icon={<Mail size={18} color="#1a5c38" />}
            title="Mahima — Frontend"
            desc="UI, Face Recognition API, Voice API, Result Analysis"
            contact="mahima@smarthire.ai"
            bg="rgba(26,92,56,0.08)"
          />
          <ContactCard
            icon={<Database size={18} color="#3b82f6" />}
            title="Anuruddha — Backend"
            desc="NLP Model, PDF Extraction, Neo4j Mapping, Screening"
            contact="anuruddha@smarthire.ai"
            bg="rgba(59,130,246,0.08)"
          />
        </div>
      </div>

      {/* Version */}
      <div style={{ textAlign: 'center', padding: '1rem 0', borderTop: '1px solid var(--border)' }}>
        <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
          SmartHire Insights · v1.0.0 · Built with React 19, Vite 8, Tailwind CSS 4
        </p>
      </div>
    </div>
  );
};

/* ── Guide card ───────────────────────────────────────────────── */
const GuideCard = ({ guide: g, delay }) => (
  <div className="card animate-fade-up" style={{ padding: '1.5rem', animationDelay: `${delay}ms` }}>
    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1.25rem' }}>
      <div style={{ width: '38px', height: '38px', borderRadius: 'var(--r-md)', background: `${g.color}18`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
        <g.icon size={18} color={g.color} />
      </div>
      <h4 style={{ fontSize: '0.9rem', fontWeight: '700' }}>{g.title}</h4>
    </div>
    <ol style={{ paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
      {g.steps.map((step, i) => (
        <li key={i} style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: '1.5' }}>{step}</li>
      ))}
    </ol>
  </div>
);

/* ── FAQ item ─────────────────────────────────────────────────── */
const FaqItem = ({ faq, open, onToggle }) => (
  <div className="card" style={{ overflow: 'hidden' }}>
    <button
      onClick={onToggle}
      style={{
        width: '100%', display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        padding: '1rem 1.25rem', background: 'none', textAlign: 'left', gap: '1rem',
      }}
    >
      <span style={{ fontSize: '0.875rem', fontWeight: '600' }}>{faq.q}</span>
      <div style={{ flexShrink: 0, color: 'var(--text-muted)', transition: 'transform 0.2s var(--ease)', transform: open ? 'rotate(180deg)' : 'rotate(0deg)' }}>
        <ChevronDown size={16} />
      </div>
    </button>
    {open && (
      <div className="animate-fade-down" style={{ padding: '0 1.25rem 1.25rem', borderTop: '1px solid var(--border)' }}>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: '1.65', paddingTop: '1rem' }}>{faq.a}</p>
      </div>
    )}
  </div>
);

/* ── Contact card ─────────────────────────────────────────────── */
const ContactCard = ({ icon, title, desc, contact, bg }) => (
  <div className="card" style={{ padding: '1.25rem' }}>
    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
      <div style={{ width: '38px', height: '38px', borderRadius: 'var(--r-md)', background: bg, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
        {icon}
      </div>
      <p style={{ fontWeight: '700', fontSize: '0.88rem' }}>{title}</p>
    </div>
    <p style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', marginBottom: '0.625rem', lineHeight: '1.5' }}>{desc}</p>
    <p style={{ fontSize: '0.78rem', color: 'var(--primary)', fontFamily: 'var(--font-mono)' }}>{contact}</p>
  </div>
);

export default Help;
